### ISSUE TITLE
Any chance this package might be updated for Nova 4?

### ISSUE THREAD

**Issue by ziming** [outl1ne/nova-detached-filters#24]
Any chance this package might be updated for Nova 4?

Thank you! Love your other packages so far

**Comment by eugenevdm** [comment]
Also super keen. Wish I had the knowledge to do a pull request, but the VueJS stuff goes over my head. For me the killer feature is the ability to save the state of the search.

**Comment by philipbaginski** [comment]
1+ :-)

**Comment by internetbug256** [comment]
Same here. I still don't understand why Nova authors aren't considering the fact that we all need and use persistent filters.

**Comment by ycoloma-etionic** [comment]
+10

**Comment by KasparRosin** [comment]
We have quite a big backlog of packages that require upgrading to support nova v4 (we had total of 34 packages, some by now have been updated to support nova v4). Currently updating them one by one based on the internal usage.

Pull requests are welcome.

**Comment by KasparRosin** [comment]
Created v4 branch, where you can track the progress.

Current progress:
- [x] The component can be used (supports vue3)
- [x] Filter state is being stored to query parameters
- [ ] Filter state is persisted to localStorage 
- [ ] Filter state is synced with dropdown filter menu
- [ ] Clear filter and other helpers work as expected and are tested.

**Comment by philipbaginski** [comment]
> Created v4 branch, where you can track the progress.
> 
> Current progress:
> 
> * [x]  The component can be used (supports vue3, filters are applied)
> * [x]  Filter state is being saved to query parameters
> * [ ]  Filter state is persisted to localStorage
> * [ ]  Filter state is synced with dropdown filter menu
> * [ ]  Clear filter and other helpers work as expected and are tested.
> * [ ]  Update broken styles
> * [ ]  Support dark theme

Is it ready to install with Nova 4 or we have to wait a little bit?

**Comment by eugenevdm** [comment]
@philipbaginski it looks like that current progress has 2/7 items completed. So I imagine 5 items are incomplete, and it would be better to wait or do a pull request and see if you can work on any of them.

**Comment by KasparRosin** [comment]
Added another patch of changes.
Currently there are two things that in-progress/not-ready.

1. Resources per page selector.
2. Filter syncing. 

I'll do a final round of testing today/tomorrow and then create a release.
It should be usable now.

**Comment by KasparRosin** [comment]
Regarding filter syncing, there seems to be an issue where if you change or reset filters from the dropdown menu, the filters in detached card will show old values and not update. Same will apply vise-versa. Because filters are built on vuex, I'm assuming there might be an issue within store somewhere. 

I'm pretty sure this worked in version 3 of laravel nova, so I'll need to debug some more, to see where is the problem.

**Comment by ycoloma-etionic** [comment]
thanks for the quick update man, cant wait to try it out

**Comment by philipbaginski** [comment]
> Regarding filter syncing, there seems to be an issue where if you change or reset filters from the dropdown menu, the filters in detached card will show old values and not update. Same will apply vise-versa. Because filters are built on vuex, I'm assuming there might be an issue within the store implementation somewhere. 
> 
> 
> 
> I'm pretty sure this worked in version 3 of laravel nova, so I'll need to debug some more, to see where is the problem.

😍

**Comment by philipbaginski** [comment]
> Added another patch of changes.
> 
> Currently there are two things that in-progress/not-ready.
> 
> 
> 
> 1. Resources per page selector.
> 
> 2. Filter syncing. 
> 
> 
> 
> I'll do a final round of testing today/tomorrow and then create a release and update documentation.
> 
> It should be usable now.

😍

**Comment by KasparRosin** [comment]
Created an issue in the nova-issues repository regarding filters and their values.
Hopefully somebody from there can shed some additional light as to why it broke with nova 4.
laravel/nova-issues#4495

**Comment by ziming** [comment]
I see you have merged and tagged it, does it mean it is fixed already? :D

**Comment by KasparRosin** [comment]
It's not fixed, but due to it not affecting most users, I decided to release it.
I will only affect you, if you are using the same filter twice.

**Comment by KasparRosin** [comment]
Moving any further conversation about nova 4 support to this discussion.
https://github.com/outl1ne/nova-detached-filters/discussions/27

**Comment by philipbaginski** [comment]
But: I have to date filters and reset works with them :-) Bright side of the issue ;-) Any progress with Nova devs to fix this problem?
